/*Queries that provide answers to the questions from all projects.*/

SELECT * from animals WHERE name = 'Luna';



/*QUERY TO FIND ALL ANIMALS WHOSE NAME ENDS IN MON*/
SELECT name 
FROM animals 
WHERE name LIKE '%mon';

/*QUERY TO FIND NAME OF ALL ANIMALS BORN BETWWEEN 2016 AND 2019*/
SELECT name
FROM animals
WHERE date_of_birth BETWEEN'2016-01-01'AND'2019-12-30'
;
/*QUERY TO FIND NAME OF ANIMALS THAT ARE NEUTERED AND HAVE LESS THAN 3 ESCAPE ATTEMPTS*/
SELECT name
FROM animals
WHERE neutered = 1 AND
escape_attempts < 3;

/*QUERY TO FIND DATE OF BIRTH OF ANIMALS WHOSE NAME IS EITHER AUGUMON OR PIKACHU*/
SELECT date_of_birth
FROM animals
WHERE name IN ('Agumon','Pikachu')
;

/*QUERY TO FIND THE NAME AND ESCAPE ATTEMPTS OF ANIMALS WEIGHING MORE THAN 10.5KG*/
SELECT name , escape_attempts
FROM animals 
WHERE weight_kg > 10.5
;

/*QUERY TO FIND ANIMALS THAT ARE NEUTERED*/
SELECT *
FROM animals
WHERE neutered = 1
;

/*QUERY TO FIND ANIMALS NOT NAMED GABUMON*/
SELECT *
FROM animals 
WHERE name <> 'Gabumon'
;

/*QUERY TO FIND ANIMALS WEIGHING BETWEEN 10.4KG AND 17.3KG(10.4KG AND 17.3KG INCLUSIVE*/
SELECT *
FROM animals
WHERE weight_kg >= 10.4 AND 
weight_kg <= 17.3
;

